name: feather
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  go_router: ^17.0.1
  provider: ^6.1.5+1
  http: ^1.6.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  google_fonts: ^7.0.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  weather_icons: ^3.0.0
  shared_preferences: ^2.5.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#546E7A"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
